### PR TITLE
fix: Reconcile duplication

### LINKED ISSUE #60: Split fetching Velero Backup spec and NAB spec Validation tasks

### LINKED ISSUE #62: Consider simplifying logic in reconcile loop for NAB.
Alright, what about keeping as it is, but simplify `if`s :question: 
```go
	if reconcileExit || reconcileRequeue || reconcileErr != nil{
		return ctrl.Result{Requeue: reconcileRequeue, RequeueAfter: requeueTimeSeconds * time.Second}, reconcileErr
	}
```

_Originally posted by @mateusoliveira43 in https://github.com/migtools/oadp-non-admin/pull/54#discussion_r1591400725_

### PR DESCRIPTION
**Pull request by mateusoliveira43**
## Why the changes were made

Fixes #62 
Fixes #60 

## How to test the changes made

Run tests and check logs (`make simulation-test`) or test in a cluster following [development documentation](https://github.com/migtools/oadp-non-admin/blob/master/docs/CONTRIBUTING.md#install-from-source).

### CODE REVIEW

File: internal/common/function/function.go [hunk 1]
```diff
@@ -34,44 +34,21 @@ import (
...
-		_, _ = fmt.Println("Error merging labels:", err)
-		// TODO break?
-		return defaultLabels
-	}
-	return mergedLabels
 }
 
-// AddNonAdminBackupAnnotations return a map with both the object annotations and with the default NonAdminBackup annotations.
-// If error occurs, a map with only the default NonAdminBackup annotations is returned
-func AddNonAdminBackupAnnotations(ownerNamespace string, ownerName string, ownerUUID string, existingAnnotations map[string]string) map[string]string {
```
Comment (mpryc) [inline internal/common/function/function.go:59]: @mateusoliveira43 why to remove `mergeMaps` from this function? Similarly from AddNonAdminLabels? The idea was to be able to add labels/annotations to whatever object had in a first place and propagate this to the Velero object.

Current function is completely modified, so if the user creates objects containing already existing annotations or labels which is perfectly valid scenario, those will get overridden/lost.

Comment (mpryc) [reply internal/common/function/function.go:59]: The function name was `AddNonAdminBackupAnnotations` so Add NonAdminBackup annotations to the object annotations.

You are just modyfing this function to:

`GetNonAdminBackupDefaultAnnotations`

Comment (mateusoliveira43) [reply internal/common/function/function.go:59]: Taking `AddNonAdminBackupAnnotations` as example

It is only used here in the code, right?
https://github.com/migtools/oadp-non-admin/blob/f99b25cc3b05ab28993294947bcf5d482bc7ee5c/internal/controller/nonadminbackup_controller.go#L258

In that place, the controller is creating the Velero Backup, so, there will never be a annotation conflict, right?

Same idea for labels.

So, I removed the check from function because they were unnecessary

Comment (mpryc) [reply internal/common/function/function.go:59]: So in this case I think we don't need that function at all and we can simply specify those labels around the above code, this way we won't expose confusing public function (confising, because we don't have now confusing name that it tells it's adding labels/annotations) ?

Comment (mpryc) [reply internal/common/function/function.go:59]: or rename those functions to something more meaningful - current function of it.

Comment (mateusoliveira43) [reply internal/common/function/function.go:59]: yes, let's rename then

what is your suggestion?

Comment (mpryc) [reply internal/common/function/function.go:59]: `GetNonAdminBackupAnnotations`

File: internal/common/function/function.go [hunk 2]
```diff
@@ -34,44 +34,21 @@ import (
 	"github.com/migtools/oadp-non-admin/internal/common/constant"
 )
 
-const requiredAnnotationError = "backup does not have the required annotation '%s'"
-
-// AddNonAdminLabels return a map with both the object labels and with the default Non Admin labels.
-// If error occurs, a map with only the default Non Admin labels is returned
-func AddNonAdminLabels(labels map[string]string) map[string]string {
```
Comment (mpryc) [inline internal/common/function/function.go:41]: `GetNonAdminLabels`

**Review by mpryc — APPROVED** [review]
